apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kie-runtime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kie-runtime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kie-runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kie-runtime.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.uploadService.enabled .Values.extraEnv }}
          env:
            {{- if .Values.uploadService.enabled }}
            - name: DEV_DEPLOYMENT__UPLOAD_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "uploadService.existingSecret is required when uploadService.enabled=true" .Values.uploadService.existingSecret | quote }}
                  key: {{ required "uploadService.secretKeyName is required when uploadService.enabled=true" .Values.uploadService.secretKeyName | quote }}
            - name: DEV_DEPLOYMENT__UPLOAD_SERVICE_PORT
              value: {{ .Values.uploadService.port | quote }}
            {{- with .Values.uploadService.extractToDirectory }}
            - name: DEV_DEPLOYMENT__UPLOAD_SERVICE_EXTRACT_TO_DIR
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.uploadService.rootPath }}
            - name: ROOT_PATH
              value: {{ . | quote }}
            - name: DEV_DEPLOYMENT__UPLOAD_SERVICE_ROOT_PATH
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
